import {classEntry,setupClass} from './bussola-classe.mjs?v=20261008-codice';
import {setupParticipantCertificate} from './bussola-attestato-alunno.mjs?v=20261010-all';
import {setupCatRemote} from './cat-remote.mjs?v=20261009-cat';
import {FORMAT,STORE as BASE_STORE,LABS,STAGES,AREAS,VIEWS,ZONES,ROOFS,FLOORS,OBSERVATIONS,HYPOTHESES,PHASES,find,createProject,dimensions,inBounds,layoutValid,place,surveySignature,composeSurvey,layoutSignature,testLayout,buildSignature,testWeather,heritageSignature,compareHeritage,estimate,planSignature,testPlan,latest,ready,completed,advance,invalidate,context,addNote,validProject} from './cat-core.mjs?v=20261009-cat';
import {esc,viewDrawing,planBoard,construction,heritage,heroDrawing} from './cat-visuals.mjs?v=20261009-cat';
const entry=classEntry(),entryToken=entry.alunno;
const localTest=['localhost','127.0.0.1'].includes(location.hostname)?new URLSearchParams(location.search).get('prova'):'';
const STORE=BASE_STORE+(entryToken?':alunno:'+entryToken:'')+(localTest?':prova:'+localTest:'');
const $=id=>document.getElementById(id);
const money=n=>n===null?'Da definire':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
let p,seenRevision=0,conflicted=false,memoryOnly=false,tool='suono',placementMessage='',remote,classAccess,attestato,loadedInitial=false;
const get=k=>{try{return localStorage.getItem(k);}catch{memoryOnly=true;return null;}};
const requested=new URLSearchParams(location.search).get('progetto');
const initialKey=requested&&/^[0-9a-f-]{36}$/i.test(requested)?requested:get(`${STORE}.latest`);
const initialRaw=initialKey?get(`${STORE}.${initialKey}`):null;
try{const parsed=initialRaw?JSON.parse(initialRaw):null;if(validProject(parsed)){p=parsed;loadedInitial=true;seenRevision=p.revision||0;}else if(initialRaw)localStorage.setItem(`${STORE}.unrecognised.${Date.now()}`,initialRaw);}catch{if(initialRaw){try{localStorage.setItem(`${STORE}.unrecognised.${Date.now()}`,initialRaw);}catch{}}}
p ||= createProject(!initialRaw&&requested&&/^[0-9a-f-]{36}$/i.test(requested)?requested:undefined);
const storageId=loadedInitial?initialKey:p.id;
const fingerprint=value=>{const {revision,updatedAt,...rest}=value;return JSON.stringify(rest);};
let savedFingerprint=seenRevision?fingerprint(p):null;
function openConflict(){if(!$('conflictDialog').open)$('conflictDialog').showModal();$('saveStatus').textContent='Le modifiche di questa finestra attendono la tua scelta.';}
function save(notify=true){if(conflicted)return false;try{const stored=JSON.parse(get(`${STORE}.${storageId}`)||'null');if(stored&&(stored.revision||0)!==seenRevision){conflicted=true;openConflict();return false;}const current=fingerprint(p),updated=!stored||current!==savedFingerprint;if(updated){p.revision=seenRevision+1;p.updatedAt=new Date().toISOString();localStorage.setItem(`${STORE}.${storageId}`,JSON.stringify(p));seenRevision=p.revision;savedFingerprint=current;}localStorage.setItem(`${STORE}.latest`,storageId);memoryOnly=false;if(!remote)$('saveStatus').textContent='Salvato su questo dispositivo.';$('noteCount').textContent=p.notes.length;if(notify&&updated&&remote&&(p.started||p.notes.some(n=>n.pending)))remote.changed();return true;}catch{memoryOnly=true;$('saveStatus').textContent='Il salvataggio non è disponibile. Il lavoro resta in questa pagina.';$('noteCount').textContent=p.notes.length;if(notify&&remote)remote.changed();return false;}}
window.addEventListener('storage',e=>{if(e.key!==`${STORE}.${storageId}`||!e.newValue)return;try{const other=JSON.parse(e.newValue);if(validProject(other)&&(other.revision||0)>seenRevision){conflicted=true;openConflict();}}catch{}});
$('conflictDialog').addEventListener('cancel',e=>e.preventDefault());
const choice=(kind,item,current)=>`<button id="${kind}-${item.id}" class="choice" type="button" data-${kind}="${item.id}" aria-pressed="${current===item.id}"><strong>${esc(item.label)}</strong>${item.desc?`<small>${esc(item.desc)}</small>`:''}</button>`;
const feedback=(text,warn=false)=>`<div class="feedback ${warn?'warn':''}" role="status"><p>${esc(text)}</p></div>`;
const draw=(html)=>`<div class="drawing">${html}</div>`;
const detail=(title,text)=>`<details><summary>${esc(title)}</summary><p>${esc(text)}</p></details>`;
function intro(){return `<section class="hero"><div><p class="eyebrow">CAT · Costruzioni, Ambiente e Territorio</p><h1 id="stageTitle" tabindex="-1">Come nasce un progetto?</h1><p class="lede">In questo indirizzo impari a misurare, disegnare e progettare spazi, scegliere materiali e organizzare lavori.</p><p>Con Archeodesign incontri anche il rilievo e la documentazione del patrimonio archeologico.</p><button id="start" class="primary" type="button">${p.started?'Riprendi il tuo lavoro':'Entra nello studio'} →</button></div><div class="hero-art">${heroDrawing()}<div class="hero-note"><strong>Due incarichi immaginari</strong><span>Spazio Live + Traccia T1</span></div></div></section><div class="lab-preview">${LABS.map((l,i)=>`<article><span class="num">${i+1}</span><h2>${l.label}</h2><p>${l.product}</p></article>`).join('')}</div><div class="intro-detail">${detail('Che cosa costruirai','Per Spazio Live progetterai un cortile per musica e video. Per Traccia T1 preparerai una documentazione archeologica. I cinque elaborati saranno tuoi e potrai modificarli.')}</div>`;}
function surveySheet(){return `<div class="sheet-head"><h3>${esc(p.survey.title||'Rilievo di Spazio Live')}</h3><span>${esc(find(AREAS,p.survey.area).label)} · ${dimensions(p).width} × 6 m</span></div><div class="view-sheet">${p.survey.views.map(id=>`<div class="view-panel">${viewDrawing(p,id)}<strong>${esc(find(VIEWS,id).label)}</strong></div>`).join('')}</div>`;}
function historyMarkup(runs,signature,describe){return runs.length?`<details class="history"><summary>Le prove conservate (${runs.length})</summary>${runs.map(r=>`<p>${r.signature===signature?'Versione attuale':'Versione precedente'} · ${esc(describe(r))}</p>`).join('')}</details>`:'';}
function costTable(){const e=estimate(p),roof=find(ROOFS,p.build.roof),floor=find(FLOORS,p.build.floor);return `<table class="cost-table"><caption class="helper">Quantità e prezzi inventati della prova</caption><thead><tr><th scope="col">Voce</th><th scope="col">Importo</th></tr></thead><tbody><tr><th scope="row">Suolo ${esc(floor?.label.replace('Suolo ','').toLowerCase()||'da scegliere')}<small>${e.surface} m² × ${e.floorPrice===null?'—':money(e.floorPrice)}/m²</small></th><td>${money(e.floorCost)}</td></tr><tr><th scope="row">${esc(roof?.label||'Copertura da scegliere')}<small>${e.roofArea} m² × ${e.roofPrice===null?'—':money(e.roofPrice)}/m²</small></th><td>${money(e.roofCost)}</td></tr><tr><th scope="row">Preparazione<small>Importo fisso ipotetico</small></th><td>${money(e.setup)}</td></tr></tbody></table><div class="total-card"><div><strong>${money(e.total)}</strong><small style="display:block">Stima dell’intero progetto</small></div><span>${e.surface} m²<br>di cortile</span></div>`;}
function phaseVisual(r){if(!r)return '<div class="empty">Scegli le fasi e premi «Ricalcola il piano».</div>';const phase1=r.phase==='suolo'?'Preparazione + suolo':r.phase==='copertura'?'Preparazione + copertura':'Preparazione + suolo + copertura';return `<div class="phase-line"><div class="phase-card"><span class="phase-id">Prima fase · ${phase1}</span><strong>${money(r.now)}</strong><p>Budget disponibile: ${money(r.budget)}</p>${r.gap?`<p>Servono ancora <strong style="font-size:17px">${money(r.gap)}</strong> per avviare questa fase.</p>`:`<p>Restano ${money(r.remaining)} del budget di prova.</p>`}</div>${r.later?`<div class="phase-card"><span class="phase-id">Seconda fase · ${r.phase==='suolo'?'Copertura':'Suolo'}</span><strong>${money(r.later)}</strong><p>Da finanziare: queste risorse non sono ancora disponibili.</p></div>`:''}</div>`;}
function content(s){let left='',right='',theme='',extra='';
 if(s===0){const a=dimensions(p);left=`<fieldset><legend>Quale area vuoi rilevare?</legend><div class="chips">${AREAS.map(a=>`<button id="area-${a.id}" type="button" data-area="${a.id}" aria-pressed="${p.survey.area===a.id}">${a.width} × ${a.depth} m</button>`).join('')}</div></fieldset><div class="measures">${[['larghezza','Larghezza',`${a.width} m`],['profondita','Profondità','6 m'],['ingresso','Ingresso','1,2 m']].map(([id,label,value])=>`<button id="measure-${id}" type="button" class="measure-card" data-measure="${id}" aria-pressed="${p.survey.measures.includes(id)}"><span>${label}</span><strong>${p.survey.measures.includes(id)?value:'Apri la misura'}</strong></button>`).join('')}</div><p class="helper">Un rilievo raccoglie misure e informazioni su ciò che esiste.</p>`;right=draw(viewDrawing(p,'pianta'))+`<p class="note-line">${p.survey.measures.length}/3 misure nella tua pianta.</p>`;}
 if(s===1){left=VIEWS.map(v=>`<button id="view-${v.id}" class="choice" type="button" data-view="${v.id}" aria-pressed="${p.survey.views.includes(v.id)}"><strong>${v.label}</strong><small>${v.desc}</small></button>`).join('')+`<label>Titolo della tavola, se vuoi<input id="surveyTitle" maxlength="80" value="${esc(p.survey.title)}"></label><button id="composeSurvey" class="primary" type="button" ${p.survey.views.length<2?'disabled':''}>Componi la tavola</button>`;right=p.survey.views.length?surveySheet():'<div class="empty">La tua tavola si compone con le viste che scegli.</div>';}
 if(s===2||s===3){left=`<fieldset><legend>Attività da collocare</legend><div class="chips">${ZONES.map(z=>`<button id="tool-${z.id}" type="button" data-tool="${z.id}" aria-pressed="${tool===z.id}">${z.label}</button>`).join('')}</div></fieldset>`;if(s===3){left+=`<fieldset><legend>Il percorso che vuoi provare</legend><div class="chips"><button id="route-bordo" type="button" data-route="bordo" aria-pressed="${p.layout.route==='bordo'}">Lungo il bordo</button><button id="route-centre" type="button" data-route="centre" aria-pressed="${p.layout.route==='centre'}">Al centro</button></div></fieldset><button id="testLayout" class="primary" type="button" ${layoutValid(p)?'':'disabled'}>Prova il passaggio</button>`;const r=latest(p.layout.runs,layoutSignature(p));if(r)extra=feedback(r.messages.join(' '),r.conflicts.length>0);left+=historyMarkup(p.layout.runs,layoutSignature(p),r=>r.conflicts.length?`${r.conflicts.join(', ')} sul passaggio`:'Passaggio libero dalle zone');}right=`<div class="map-controls">${left}</div>`+planBoard(p,{active:true,showRoute:s===3,tool})+(placementMessage?feedback(placementMessage,true):'')+extra+(s===2?detail('La richiesta di Spazio Live','Nel cortile si registrano video, si prova musica e si montano contenuti. Chi entra deve poter passare fra le attività. La griglia è semplificata: in un progetto reale si verificano più vincoli.'):'');left='';if(!layoutValid(p)&&ZONES.some(z=>p.layout.zones[z.id]&&!inBounds(p,p.layout.zones[z.id])))right+=feedback('Hai scelto un’area più piccola: ricolloca le attività che sono fuori dalla pianta.',true);}
 if(s===4||s===5){const selection=ROOFS.map(r=>choice('roof',r,p.build.roof)).join('')+FLOORS.map(f=>choice('floor',f,p.build.floor)).join('')+`<fieldset><legend>Quanta superficie vuoi coprire?</legend><div class="chips">${[4,8,12].map(n=>`<button id="cover-${n}" type="button" data-cover="${n}" aria-pressed="${p.build.cover===n}">${n} m²</button>`).join('')}</div></fieldset>`;if(s===4)left=selection;if(s===5)left=`<div class="button-row"><button id="weather-sole" class="action" type="button" data-weather="sole">Prova il sole</button><button id="weather-pioggia" class="action" type="button" data-weather="pioggia">Prova la pioggia</button></div><details><summary>Rivedi materiali e superficie</summary><div class="controls">${selection}</div></details>`;const r=latest(p.build.runs,buildSignature(p));right=draw(construction(p,s===5?r?.weather:null));if(s===5){right+=r?feedback(r.text):'<p class="note-line">Premi una delle due prove per osservare il modello.</p>';left+=historyMarkup(p.build.runs,buildSignature(p),r=>r.weather==='sole'?'Sole':'Pioggia');}right+=`<p class="helper" style="margin-top:12px">Modello qualitativo. Non calcola resistenza, calore o infiltrazione reale.</p>`;theme='mint';}
 if(s===6){left=OBSERVATIONS.map(o=>`<button id="observe-${o.id}" class="choice" data-observe="${o.id}" type="button" aria-pressed="${p.heritage.observations.includes(o.id)}"><strong>${o.label}</strong>${p.heritage.observations.includes(o.id)?`<small>${o.text}</small>`:'<small>Apri la scheda</small>'}</button>`).join('');right=draw(heritage(p,{hypothesis:false}))+`<p class="note-line">${p.heritage.observations.length}/3 schede nel dossier.</p><p class="helper">Manufatto inventato. Le viste sono illustrazioni; le misure sono fornite nella prova.</p>`;theme='sand';}
 if(s===7){left=HYPOTHESES.map(h=>choice('hypothesis',h,p.heritage.hypothesis)).join('')+`<fieldset><legend>Come distingui la parte ipotizzata?</legend><div class="chips"><button id="encoding-tratto" data-encoding="tratto" type="button" aria-pressed="${p.heritage.encoding==='tratto'}">Tratteggio</button><button id="encoding-campitura" data-encoding="campitura" type="button" aria-pressed="${p.heritage.encoding==='campitura'}">Tratteggio e campitura</button></div><p class="helper">Campitura: riempimento di colore.</p></fieldset><button id="compareHeritage" class="primary" type="button" ${p.heritage.hypothesis?'':'disabled'}>Confronta con le tracce</button>`;right=`<div class="sheet-head"><h3>Traccia T1 · Documentazione</h3><span>Frammenti osservati e forma superiore incerta</span></div>${draw(heritage(p))}<div class="legend"><span><i></i>Parti documentate</span><span><i class="hypothesis"></i>Ipotesi, se presente</span></div>`;const r=latest(p.heritage.runs,heritageSignature(p));if(r)right+=feedback(r.text);theme='sand';}
 if(s===8){left=`<p>La superficie viene dal tuo rilievo; i componenti dal laboratorio Materiali.</p><button id="estimate" class="primary" type="button">Calcola la stima</button>${detail('Che cos’è un computo?','È un conteggio di quantità e costi. Per esempio: metri quadrati di suolo × prezzo per metro quadrato. Nel corso l’estimo comprende anche la valutazione di beni e interventi. Questi prezzi sono inventati.')}`;right=costTable();const r=latest(p.plan.runs,planSignature(p,'base'));if(r)right+=feedback(r.gap?`Il progetto supera il primo budget ipotetico di 1.200 € di ${money(r.gap)}. Puoi tenerlo come proposta e studiare le fasi.`:`La stima rientra nel primo budget ipotetico di 1.200 €. Restano ${money(r.remaining)}.`);}
 if(s===9){left=PHASES.map(ph=>choice('phase',ph,p.plan.phase)).join('')+`<button id="plan" class="primary" type="button" ${p.plan.phase?'':'disabled'}>Ricalcola il piano</button><p class="helper">I materiali restano quelli progettati. Cambia il momento in cui li realizzeresti.</p>`;const r=latest(p.plan.runs,planSignature(p,'budget'));right=phaseVisual(r)+detail('Che cosa rimane da verificare?','Prima dei lavori servono progetto tecnico, autorizzazioni e organizzazione del cantiere, compresa la sicurezza. Questa prova mostra soltanto quantità e fasi; non autorizza un intervento.');left+=historyMarkup(p.plan.runs,planSignature(p,'budget'),r=>r.kind==='base'?`Stima iniziale ${money(r.total)}`:`Prima fase ${money(r.now)}; da finanziare dopo ${money(r.later)}`);}
 return {left,right,theme};}
function activity(){const s=p.screen,l=LABS[Math.floor(s/2)],d=STAGES[s],v=content(s);return `<div class="stage-heading"><div><p class="eyebrow">Laboratorio ${Math.floor(s/2)+1} · ${l.label}</p><h1 id="stageTitle" tabindex="-1">${d[0]}</h1></div><span class="step-tag">${s%2+1} di 2</span></div><span class="client">${l.client}${s===6?' · Nuovo incarico':s===8?' · Torni al tuo progetto':''}</span><p class="stage-intro">${d[1]}</p><div class="workgrid ${v.left?'':'single'}">${v.left?`<section class="controls" aria-label="Che cosa fare adesso">${v.left}</section>`:''}<section class="canvas ${v.theme}" aria-label="Il tuo elaborato"><span class="canvas-label">${l.product}</span>${v.right}</section></div><div class="stage-nav"><button id="previous" class="quiet" type="button">← Indietro</button><p id="advanceHelp">${ready(p)?'Puoi continuare o rivedere le scelte.':d[2]}</p><button id="next" class="primary" type="button" ${ready(p)?'':'disabled'} aria-describedby="advanceHelp">${d[3]} →</button></div><p class="subjects">Materie di indirizzo e collegamenti: ${l.subjects}.</p>`;}
function interestText(){return p.interests.length?`Hai indicato ${p.interests.map(id=>find(LABS,id).label).join(', ')}. Una domanda da portare alla scuola: «Quali progetti si fanno su questi aspetti nel corso CAT Archeodesign?»`:'Quale elaborato ti ha incuriosito? Che cosa vorresti creare ancora?';}
function resultCard(n,title,short,body){return `<article class="end-card"><details><summary><span class="eyebrow">${n} · ${esc(LABS[n-1].label)}</span><strong>${esc(title)}</strong><span class="result-short">${esc(short)}</span></summary><div class="result-body">${body}</div></details></article>`;}
function end(){const pending=LABS.filter((l,i)=>![i*2,i*2+1].every(s=>ready(p,s)&&p.done.includes(s))),lr=latest(p.layout.runs,layoutSignature(p)),hr=latest(p.heritage.runs,heritageSignature(p)),pr=latest(p.plan.runs,planSignature(p,'budget'));
 const cards=[
 resultCard(1,'La tua tavola di rilievo',`${dimensions(p).width} × 6 m · ${p.survey.views.map(id=>find(VIEWS,id).label).join(', ')}`,surveySheet()+'<button class="quiet" type="button" data-goto="0">Rivedi il rilievo</button>'),
 resultCard(2,'Le attività e i passaggi','Suono, Video e Montaggio nella tua pianta',planBoard(p,{showRoute:true})+`<p>${esc(lr?.messages.join(' ')||'La disposizione attuale è da provare.')}</p><button class="quiet" type="button" data-goto="2">Rivedi gli spazi</button>`),
 resultCard(3,'La tua soluzione costruttiva',`${find(ROOFS,p.build.roof)?.label||'Copertura da scegliere'} · ${find(FLOORS,p.build.floor)?.label||'Suolo da scegliere'}`,draw(construction(p))+`<p>${p.build.cover} m² coperti.</p><button class="quiet" type="button" data-goto="4">Rivedi i materiali</button>`),
 resultCard(4,'La documentazione archeologica',`Traccia T1 · ${find(HYPOTHESES,p.heritage.hypothesis)?.label||'Da comporre'}`,draw(heritage(p))+`<p>${esc(hr?.text||'La tavola attuale è da confrontare con le tracce.')}</p><div class="legend"><span><i></i>Documentato</span><span><i class="hypothesis"></i>Ipotizzato</span></div><button class="quiet" type="button" data-goto="6">Rivedi Archeodesign</button>`),
 resultCard(5,'Il tuo piano di lavoro',`${money(estimate(p).total)} · ${find(PHASES,p.plan.phase)?.label||'Fasi da scegliere'}`,`<div class="workgrid"><div>${costTable()}</div><div>${phaseVisual(pr)}</div></div><button class="quiet" type="button" data-goto="8">Rivedi le risorse</button>`)
 ].join('');
 return `<section class="end-top"><p class="eyebrow">Cinque elaborati · Due incarichi</p><h1 id="stageTitle" tabindex="-1">Il tuo dossier di progetto.</h1><p>Hai creato cinque elaborati. Puoi aprirli qui sotto e tornare a modificarli.</p><label>Titolo del dossier, se vuoi<input id="dossierTitle" value="${esc(p.title)}" maxlength="80"></label></section>${pending.length?`<div class="pending">Hai modificato alcune scelte. Ripassa ${pending.map(l=>l.label).join(', ')} per provare la versione corrente. Le prove precedenti sono conservate.</div>`:''}<section class="interest-section"><h2>Quali parti vorresti approfondire?</h2><p>Puoi indicarne più di una.</p><div class="interests">${LABS.map(l=>`<label class="interest"><input type="checkbox" name="interest" value="${l.id}" ${p.interests.includes(l.id)?'checked':''}><span>${l.label}</span></label>`).join('')}</div><p id="interestMessage" class="interest-message">${interestText()}</p></section><div class="certificate-cta"><button id="certificateOpen" class="primary" type="button" ${completed(p)?'':'disabled'}>Visualizza il tuo attestato</button><p>Puoi stamparlo o scaricarlo in PDF sul dispositivo.</p></div><div class="end-grid">${cards}</div>`;}

function recovery(){let items=[];try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith(`${STORE}.`)||key.includes('latest')||key.includes('unrecognised'))continue;try{const x=JSON.parse(localStorage.getItem(key));if(validProject(x))items.push({...x,storageKey:key.slice(STORE.length+1)});}catch{}}}catch{}items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('previousProjects').innerHTML=items.map(x=>`<option value="${x.storageKey}" ${x.storageKey===storageId?'selected':''}>${esc(x.title||'Nuova prova')} · ${new Date(x.updatedAt||Date.now()).toLocaleString('it-IT')} ${x.id===p.id?'· attuale':''}</option>`).join('');}
function render(focus=false,notify=true){const active=document.activeElement?.id;$('journey').innerHTML=p.started?LABS.map((l,i)=>`<button id="lab-${i}" type="button" data-goto="${i*2}" ${p.unlocked<i*2?'disabled':''} ${p.screen>=i*2&&p.screen<i*2+2?'aria-current="step"':''} aria-label="${l.label}" class="${[i*2,i*2+1].every(s=>ready(p,s)&&p.done.includes(s))?'done':''}"><span>${i+1}</span>${l.label}</button>`).join('')+(p.unlocked===10?'<button id="navDossier" data-goto="10" type="button">Dossier</button>':''):'';$('stage').innerHTML=p.screen<0?intro():p.screen===10?end():activity();const route=new URL(location.href),step=p.screen<0?'ingresso':p.screen===10?'conclusione':`passaggio-${p.screen+1}`;route.searchParams.set('progetto',storageId);route.hash=entry.classe?new URLSearchParams({classe:entry.classe,...entryToken?{alunno:entryToken}:{},passaggio:step}).toString():step;window.history.replaceState(null,'',route.href);save(notify);recovery();if(focus){$('stageTitle')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}else if(active&&$(active))$(active).focus({preventScroll:true});}
function renderNotes(){$('noteContext').value=context(p).label;$('notesList').innerHTML=p.notes.length?p.notes.map(n=>`<article class="saved-note"><small>${n.role==='docente'?'Docente':'Alunno'} · ${esc(n.kind)} · ${new Date(n.createdAt).toLocaleString('it-IT')}</small><strong>${esc(n.label)}</strong><p>${esc(n.text)}</p></article>`).join(''):'<p class="helper">Non hai ancora scritto note.</p>';}
function updateNavigation(){const n=$('next');if(n){n.disabled=!ready(p);$('advanceHelp').textContent=ready(p)?'Puoi continuare o rivedere le scelte.':STAGES[p.screen][2];}save();}
document.addEventListener('input',e=>{if(conflicted)return;const t=e.target;if(t.id==='surveyTitle'){p.survey.title=t.value.slice(0,80);invalidate(p);updateNavigation();}if(t.id==='dossierTitle'){p.title=t.value.slice(0,80);save();}});
document.addEventListener('change',e=>{if(conflicted)return;const t=e.target;if(t.name==='interest'){p.interests=t.checked?[...new Set([...p.interests,t.value])]:p.interests.filter(id=>id!==t.value);save();$('interestMessage').textContent=interestText();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.close){$(b.dataset.close).close();return;}
 if(b.id==='reloadConflict'){
  if(remote.hasConflict()){try{await remote.reload();conflicted=false;$('conflictDialog').close();render(true);}catch{$('saveStatus').textContent='La versione recente non è disponibile. La tua copia è conservata.';}return;}
  const other=JSON.parse(get(`${STORE}.${storageId}`)||'null');if(validProject(other)){p=other;seenRevision=p.revision||0;savedFingerprint=fingerprint(p);conflicted=false;$('conflictDialog').close();render(true);}return;
 }
 if(b.id==='copyConflict'){
  const copy=JSON.parse(JSON.stringify(p));copy.id=crypto.randomUUID();copy.identity=null;copy.notes=copy.notes.map(n=>({...n,id:crypto.randomUUID(),copiedFrom:n.id,projectId:copy.id,pending:true}));copy.title=(copy.title+' · copia').slice(0,80);copy.revision=1;
  try{const copyStore=BASE_STORE+(localTest?':prova:'+localTest:'');localStorage.setItem(`${copyStore}.${copy.id}`,JSON.stringify(copy));const u=new URL(location.href);u.searchParams.set('progetto',copy.id);u.hash='ingresso';location.assign(u.href);}catch{$('saveStatus').textContent='Il dispositivo non permette di conservare la copia. Tieni aperta questa finestra.';}return;
 }
 if(conflicted)return;
 if(b.id==='notesOpen'){renderNotes();$('noteStatus').textContent='';$('notesDialog').showModal();return;}
 if(b.dataset.goto!==undefined){const s=Number(b.dataset.goto);if(Number.isInteger(s)&&s>=0&&s<=p.unlocked){p.screen=s;placementMessage='';render(true);}return;}
 if(b.id==='start'){if(p.started){p.screen=Math.min(p.unlocked,10);render(true);}else{classAccess.begin(b);}return;}
 if(b.id==='previous'){p.screen=Math.max(-1,p.screen-1);placementMessage='';render(true);return;}
 if(b.id==='next'){if(advance(p)){placementMessage='';render(true);}return;}
 if(b.dataset.area){p.survey.area=b.dataset.area;p.survey.measures=[];invalidate(p);render();return;}
 if(b.dataset.measure){const id=b.dataset.measure;if(!p.survey.measures.includes(id))p.survey.measures.push(id);invalidate(p);render();return;}
 if(b.dataset.view){const id=b.dataset.view;p.survey.views=p.survey.views.includes(id)?p.survey.views.filter(x=>x!==id):[...p.survey.views,id];invalidate(p);render();return;}
 if(b.id==='composeSurvey'){composeSurvey(p);render();return;}
 if(b.dataset.tool){tool=b.dataset.tool;placementMessage='';render();return;}
 if(b.dataset.cellX!==undefined){const ok=place(p,tool,Number(b.dataset.cellX),Number(b.dataset.cellY));placementMessage=ok?'':'La casella è occupata. Scegli una casella libera o sposta prima l’altra attività.';render();return;}
 if(b.dataset.route){p.layout.route=b.dataset.route;invalidate(p);render();return;}
 if(b.id==='testLayout'){testLayout(p);render();return;}
 if(b.dataset.roof||b.dataset.floor||b.dataset.cover){if(b.dataset.roof)p.build.roof=b.dataset.roof;if(b.dataset.floor)p.build.floor=b.dataset.floor;if(b.dataset.cover)p.build.cover=Number(b.dataset.cover);invalidate(p);render();return;}
 if(b.dataset.weather){testWeather(p,b.dataset.weather);render();return;}
 if(b.dataset.observe){if(!p.heritage.observations.includes(b.dataset.observe))p.heritage.observations.push(b.dataset.observe);invalidate(p);render();return;}
 if(b.dataset.hypothesis){p.heritage.hypothesis=b.dataset.hypothesis;invalidate(p);render();return;}
 if(b.dataset.encoding){p.heritage.encoding=b.dataset.encoding;invalidate(p);render();return;}
 if(b.id==='compareHeritage'){compareHeritage(p);render();return;}
 if(b.id==='estimate'){testPlan(p,'base');render();return;}
 if(b.dataset.phase){p.plan.phase=b.dataset.phase;invalidate(p);render();return;}
 if(b.id==='plan'){testPlan(p,'budget');render();return;}
 if(b.id==='certificateOpen'&&completed(p)){save();attestato.open(b);return;}
 if(b.id==='newProject'){save();const u=new URL(location.href);u.searchParams.set('progetto',crypto.randomUUID());u.hash='ingresso';location.assign(u.href);return;}
 if(b.id==='recover'){const id=$('previousProjects').value,other=JSON.parse(get(`${STORE}.${id}`)||'null');if(validProject(other)){save();const u=new URL(location.href);u.searchParams.set('progetto',id);u.hash='ingresso';location.assign(u.href);}return;}

});
$('noteForm').addEventListener('submit',e=>{e.preventDefault();if(conflicted)return;const note=addNote(p,Object.fromEntries(new FormData(e.target)));if(note){note.pending=true;const ok=save();renderNotes();e.target.elements.text.value='';$('noteStatus').textContent=ok?'Nota conservata; aggiornamento online in corso.':'La nota resta in questa pagina: il browser non permette il salvataggio.';}});
function loaded(value){p=value;p.revision=seenRevision;render(false,false);}
remote=setupCatRemote({key:STORE+'.remote.'+storageId,entryToken,project:()=>p,keep:()=>save(false),loaded,localOK:()=>!memoryOnly,status:(text,retry)=>{$('saveStatus').textContent=text;$('retrySave').hidden=!retry;},notesChanged:()=>{$('noteCount').textContent=p.notes.length;if($('notesDialog').open)renderNotes();},conflict:()=>{conflicted=true;openConflict();}});
classAccess=setupClass({key:STORE+'.'+storageId,token:()=>remote.token(),ensure:()=>remote.ensure(),isIntro:()=>p.screen<0,start:async()=>{try{await remote.ensure();}catch{}p.started=true;p.screen=Math.max(0,p.screen);render(true);}});
attestato=setupParticipantCertificate({project:()=>p,journey:()=>p,save,identity:()=>classAccess.identity(),participant:()=>remote.participant(),revision:()=>remote.revision()});
$('retrySave').addEventListener('click',()=>remote.sync());
window.addEventListener('online',()=>remote.sync());
render(false,false);if(remote.token())remote.sync();
