import {classEntry,setupClass} from './bussola-classe.mjs?v=20261008-codice';
import {setupParticipantCertificate} from './bussola-attestato-alunno.mjs?v=20261009-cat';
import {GUIDE,cursor,guideIssues,titleDefaults,storyBranch} from './ssas-guided-core.mjs';
import {LAB_PRESENTATION,studioArt} from './ssas-labs-visuals.mjs?v=20261010-ssas';
import {FORMAT,LABS,CONDITIONS,OPENINGS,PARTICIPATION,PERSONS,GOALS,SETTINGS,SERVICES,ACCESS,CHECKS,freshProject,restoreProject,issues,beginRevision,summaryItems,xml} from './ssas-labs-core.mjs?v=20261008';
const localTest=['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).get('prova');
const API=localTest?'/__test/bussola-esperienze':'https://ruplzgcnheddmqqdephp.supabase.co/functions/v1/bussola-esperienze';
const entryAlumno=classEntry().alunno;
const KEY='bussola-ssas-cinque-laboratori-v1'+(entryAlumno?':alunno:'+entryAlumno:'')+(localTest?':prova:'+localTest.replace(/[^a-z0-9-]/gi,'').slice(0,60):'');
const mount=document.getElementById('workspace'), nav=document.getElementById('stepNav');
const saveStatus=document.getElementById('saveStatus'),retry=document.getElementById('retrySave');
const notesDialog=document.getElementById('notesDialog');
const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
const btn=(text,fn,cls='primary')=>{const n=node('button',text,cls);n.type='button';n.addEventListener('click',fn);return n;};
const label=(text,control)=>{const n=node('label',text,'field');control.setAttribute('aria-label',text);n.append(control);return n;};
const unique=x=>[...new Map(x.map(v=>[v.id,v])).values()];
const copy=x=>JSON.parse(JSON.stringify(x));
const fileCache=new Map();
function fileURL(content,type){const previous=fileCache.get(type);if(previous?.content===content)return previous.url;const url=URL.createObjectURL(new Blob([content],{type}));fileCache.set(type,{content,url});if(previous)setTimeout(()=>URL.revokeObjectURL(previous.url),60000);return url;}
let localOK=true, connected=false, syncing=false, conflict=false, clock=0, timer, epoch=0, noteTrigger;
let state={project:freshProject(),token:'',participant:'',revision:0,dirty:false,notes:[],draft:null};
try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw&&typeof raw==='object')state={...state,...raw,project:restoreProject(raw.project),token:/^[\w-]{43}$/.test(raw.token)?raw.token:'',revision:Number.isInteger(raw.revision)?raw.revision:0,notes:Array.isArray(raw.notes)?raw.notes.filter(n=>n&&typeof n.testo==='string'):[]};}catch{}
if(entryAlumno&&!state.token)state.token=entryAlumno;
function keep(){try{localStorage.setItem(KEY,JSON.stringify(state));localOK=true;}catch{localOK=false;}}
function status(text,error=false){saveStatus.textContent=localTest?text.replaceAll('Supabase','database di prova')+' · Prova locale':text;$('saveStatus').parentElement.dataset.error=String(error);retry.hidden=!error||conflict;}
function newToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
async function call(action,payload={}){
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);
 try{
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','x-bussola-token':state.token},body:JSON.stringify({action,...payload}),signal:controller.signal});
  const body=await r.json();if(!r.ok){const e=new Error(body.error||'Salvataggio non disponibile.');e.code=r.status;throw e;}return body;
 }finally{clearTimeout(timeout);}
}
async function connect(){
 if(!state.token){state.token=newToken();keep();}
 const generation=epoch,reply=await call('start');if(generation!==epoch)return;
 if(reply.project&&state.dirty&&reply.project.revision!==state.revision){
  if(state.lastOp&&reply.project.payload?._save_operation===state.lastOp)state.revision=reply.project.revision;
  else{conflict=true;throw Object.assign(new Error('Il progetto è cambiato in un’altra finestra. Scarica il tuo lavoro prima di ricaricare.'),{code:409});}
 }
 state.participant=reply.participant;
 if(reply.project&&!state.dirty){state.project=restoreProject(reply.project.payload);state.revision=reply.project.revision;render(false);}
 state.notes=unique([...state.notes.filter(n=>n.pending),...(reply.notes||[]).map(n=>({...n,pending:false}))]);
 connected=true;keep();renderNotes();
}
async function sync(){
 if(syncing||conflict)return;
 syncing=true;const generation=epoch;status('Salvataggio in corso…');
 try{
  if(!connected)await connect();if(generation!==epoch)return;
  while(state.dirty){
   const stamp=clock,snapshot=copy(state.project);state.lastOp=crypto.randomUUID();snapshot._save_operation=state.lastOp;keep();
   const reply=await call('save',{project:snapshot,revision:state.revision});
   if(generation!==epoch)return;state.revision=reply.revision;
   if(stamp===clock)state.dirty=false;keep();
  }
  for(const n of state.notes.filter(x=>x.pending)){
   const reply=await call('note',{note:n});if(generation!==epoch)return;
   n.pending=false;n.created_at=reply.note.created_at;keep();
  }
  renderNotes();status(state.notes.some(n=>n.pending)?'Una nuova nota è in attesa di salvataggio…':localOK?'Tutto salvato. Puoi riprendere da questo dispositivo.':'Salvato online. Questo browser non conserva l’accesso: scarica una copia prima di chiudere.');
 }catch(e){
  if(generation!==epoch)return;
  if(e.code===409)conflict=true;
  const message=conflict?e.message:localOK?'Il lavoro è sul dispositivo. Il salvataggio online è da riprovare.':'Il lavoro è ancora aperto. Scarica una copia: il salvataggio non è riuscito.';
  status(message,true);renderNotes();
 }finally{syncing=false;if(!conflict&&(state.dirty||state.notes.some(n=>n.pending))&&(generation!==epoch||(connected&&saveStatus.parentElement.dataset.error!=='true')))schedule();}
}
function schedule(){clearTimeout(timer);timer=setTimeout(sync,600);}
function changed(redraw=false,complete=false){
 if(!complete)journey().finished=false;clock++;state.dirty=true;keep();
 status(localOK?'Salvato sul dispositivo · aggiornamento in corso…':'Salvataggio sul dispositivo non disponibile.');schedule();
 updateLive();updateHelp();if(journey().step===6&&!redraw){const next=$('continue');if(next){next.disabled=journey().finished||guideIssues(journey()).length>0;next.textContent=journey().finished?'Percorso concluso ✓':'Concludi il percorso';}if(!journey().finished)$('completion')?.remove();}if(redraw)render(false);
}

const journey=()=>state.project.labJourney;
const noteStep=()=>Math.min(5,journey().step);
const areaKeys=['health','relation','autonomy','creative','service'];
const iconPaths={salute:'M12 4v16M4 12h16M9 4H6v5H2v6h4v5h5v-4h5v-5h4V9h-4V4h-5',relazione:'M4 5h16v11H10l-5 4v-4H4ZM8 9h8M8 12h5',autonomia:'M5 12l4 4L20 5M4 4h6M4 4v6M20 20h-6M20 20v-6',creativita:'M4 19l4-1L20 6l-4-4L4 14ZM14 4l4 4M3 22h18',progettazione:'M3 3h7v6H3ZM14 15h7v6h-7ZM6 9v9h8M14 3h7v6h-7M17 9v6'};
function symbol(id){const n=node('span',null,'lab-symbol');n.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[id]}" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round" stroke-linecap="round"/></svg>`;return n;}
function sheet(title,description){const s=node('section',null,'sheet');s.append(node('h2',title));if(description)s.append(node('p',description));return s;}
function edit(area,key,value,redraw=true){const j=journey(),p=j[area];
 if(p[key]===value)return;
 if((area==='health'&&key==='focus')||(area==='autonomy'&&key==='person')||(area==='service'&&key==='kind')){
  const {alternatives,...current}=p;p.alternatives={...p.alternatives};if(p[key])p.alternatives[p[key]]=copy(current);
  const previous=p.alternatives[value];
  if(area==='health'){p.title=previous?.title||'';p.explanation=previous?.explanation||'';p.before=previous?.before||null;}
  if(area==='autonomy'){p.supports=previous?.supports||[];p.adaptation=previous?.adaptation||'';p.before=previous?.before||null;}
  if(area==='service'){p.name=previous?.name||'';p.activity=previous?.activity||'';p.access=previous?.access||'';p.check=previous?.check||'';p.before=previous?.before||null;}
 }
 if(area==='creative'&&['goal','setting'].includes(key)){if(p.ending)p.previousEndings=[...new Set([...(p.previousEndings||[]),p.ending])].slice(-8);p.ending='';p.before=null;}
 p[key]=value;j.done=j.done.filter(id=>id!==LABS[areaKeys.indexOf(area)].id);changed(redraw);
}
function choose(arr,area,key,{check=false,compact=false,prefix=''}={}){const box=node('fieldset',null,`choices${compact?' compact-choices':''}`);box.append(node('legend',GUIDE[journey().step-1]?.[cursor(journey())]||'Scegli una proposta','sr-only'));box.id=`${area}-${key}`;
 for(const item of arr){const input=node('input');input.type=check?'checkbox':'radio';input.id=`${area}-${key}-${item.id}`;input.name=`ssas-${area}-${key}`;input.value=item.id;input.checked=check?journey()[area][key].includes(item.id):journey()[area][key]===item.id;
 input.addEventListener('change',()=>{if(check){const values=journey()[area][key];edit(area,key,input.checked?[...values,item.id]:values.filter(x=>x!==item.id));}else edit(area,key,item.id);});const l=node('label',null,'choice');l.append(input);const c=node('span');c.append(node('strong',prefix+(item.label||item.name)));if(item.detail||item.group)c.append(node('small',item.detail||item.group));l.append(c);box.append(l);}return box;}
function field(title,area,key,max=180,multiline=false){const c=node(multiline?'textarea':'input');if(!multiline)c.type='text';else c.rows=3;c.name=`ssas-${area}-${key}`;c.id=`${area}-${key}`;c.maxLength=max;c.value=journey()[area][key];c.addEventListener('input',()=>edit(area,key,c.value,false));return label(title,c,'field');}
// Keep field labels explicit; the reusable helper above adds both association and an accessible name.
function examples(texts,area,key){const list=node('div',null,'example-buttons');texts.forEach((text,i)=>list.append(btn(`Usa l’esempio ${i+1}`,()=>edit(area,key,text),'secondary')));return list;}
function exampleChoices(texts,area,key){const d=node('div',null,'choices');texts.forEach((text,i)=>{const b=btn(text,()=>{if(area==='creative'&&key==='ending')journey().creative.editedBranch=i;edit(area,key,text);},'secondary');b.id=`example-${area}-${key}-${i}`;d.append(b);});return d;}
function info(title,text){const c=node('div',null,'micro-card');c.append(node('h3',title),node('p',text));return c;}
function svgWrap(content,title,description){
 const captions=[...content.matchAll(/<text[^>]*>([\s\S]*?)<\/text>/g)].map(m=>m[1]);
 const shapes=content.replace(/<text[^>]*>[\s\S]*?<\/text>/g,'');
 return `<figure class="illustration"><svg viewBox="0 0 440 245" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${xml(title+'. '+description)}"><rect width="440" height="245" rx="16" fill="#e1edf2"/>${shapes}</svg>${captions.length?`<figcaption>${captions.map(t=>`<span>${t}</span>`).join('')}</figcaption>`:''}</figure>`;
}
function conditionDiagram(id,change){if(id==='asma')return svgWrap(`<text x="22" y="28" fill="#554f45" font-family="Arial" font-size="12">${change?'Vie respiratorie nell’asma':'Il passaggio dell’aria'}</text><path d="M200 45v50m0-10L150 122m50-37 50 37" fill="none" stroke="#b27467" stroke-width="12"/><path d="M176 91C143 53 73 103 75 163s44 75 98 38Z" fill="#d59b88"/><path d="M224 91c33-38 103 12 101 72s-44 75-98 38Z" fill="#d59b88"/><path d="M160 127l-30 25m-5-13v39m105-51 30 25m5-13v39" fill="none" stroke="#fff2db" stroke-width="7"/><circle cx="365" cy="114" r="40" fill="#b16f61"/><circle cx="365" cy="114" r="${change?16:30}" fill="#fff4dd"/><path d="M285 150l43-15" stroke="#658573" stroke-width="2" stroke-dasharray="4 4"/><text x="318" y="177" fill="#554f45" font-family="Arial" font-size="11">Bronco in sezione</text><path d="M28 80h34m-12-6 12 6-12 6" stroke="#507d80" stroke-width="3" fill="none"/><text x="22" y="225" fill="#554f45" font-family="Arial" font-size="11">${change?'Il lume, lo spazio interno, può restringersi.':'L’aria passa attraverso le vie respiratorie.'}</text>`, 'Polmoni e bronco',change?'Confronto schematico: lume del bronco ridotto.':'Confronto schematico: passaggio dell’aria aperto.');
 const brain=`<path d="M165 55c-34-13-68 20-53 48-24 29-4 65 28 61 12 31 49 27 61 9 26 19 54-4 50-24 36-8 31-49 5-58 9-29-27-58-55-40-15-11-24-9-36 4Z" fill="#cda996" stroke="#8c655b" stroke-width="2"/><path d="M159 64c-15 12 2 35 13 33m28-40v109m19-97c25 4 4 35 13 48m-100 9c21-9 35 17 22 31" stroke="#8c655b" stroke-width="2" fill="none"/>`;
 if(id==='paralisi')return svgWrap(`${brain}<path d="M211 177v30m-18 12 18-15 21 15" fill="none" stroke="#6b8170" stroke-width="4"/><circle cx="336" cy="66" r="15" fill="#af7f61"/><path d="M336 84v53m-34-30 34-9 28 25m-28 14-30 53m30-53 24 51" stroke="#586f59" stroke-width="8" stroke-linecap="round" fill="none"/><path d="M251 121h37" stroke="#956037" stroke-width="3" stroke-dasharray="5 5"/><text x="24" y="26" fill="#554f45" font-family="Arial" font-size="12">Cervello · movimento · ambiente</text><text x="23" y="234" fill="#554f45" font-family="Arial" font-size="11">${change?'I bisogni di sostegno variano tra persone.':'Il sistema nervoso coordina movimento e postura.'}</text>`, 'Cervello e controllo del movimento','Schema di una relazione funzionale, senza rappresentare una lesione individuale.');
 return svgWrap(`${brain}<g stroke="#6c8372" stroke-width="2" fill="none"><path d="M294 73l42 30 39-47m-39 47 29 43m-71-73 15 91" ${change?'stroke-dasharray="4 5"':''}/></g><g fill="${change?'#ac6b59':'#648b72'}"><circle cx="294" cy="73" r="10"/><circle cx="336" cy="103" r="10"/><circle cx="375" cy="56" r="10"/><circle cx="365" cy="146" r="10"/><circle cx="309" cy="164" r="10"/></g><text x="24" y="26" fill="#554f45" font-family="Arial" font-size="12">Cervello · memoria · attività quotidiane</text><text x="23" y="227" fill="#554f45" font-family="Arial" font-size="11">${change?'La malattia può compromettere queste funzioni.':'Le cellule nervose comunicano tra loro.'}</text>`, 'Cervello e comunicazione tra cellule','Il disegno è concettuale: non mostra un esame clinico.');}
function roomArt(){return svgWrap(`<path d="M70 84l151-47 148 68v116H70Z" fill="#faf3e4"/><path d="M221 37v122l148 62V105Z" fill="#d9c9b0"/><path d="M96 111h82v51H96Z" fill="#9cb8a3"/><ellipse cx="220" cy="172" rx="107" ry="26" fill="#b99770"/><g fill="#638471"><circle cx="128" cy="118" r="15"/><path d="M105 155q23-43 46 0"/><circle cx="286" cy="132" r="15"/><path d="M263 169q23-43 46 0"/></g><g fill="#a87766"><circle cx="213" cy="88" r="15"/><path d="M190 125q23-43 46 0"/></g><path d="M180 162h35m22 5h36" stroke="#fff5df" stroke-width="6"/>`,'Un incontro di gruppo','Tre persone attorno a un tavolo.');}
function supportArt(person,supports){const has=id=>supports.some(s=>s.id===id);let art='';
 if(person?.id==='rosa'){art=`<rect x="172" y="22" width="117" height="205" rx="17" fill="#56785f"/><rect x="181" y="42" width="99" height="157" rx="7" fill="#fff7e4"/><circle cx="230" cy="212" r="6" fill="#e9ecda"/><text x="190" y="${has('caratteri')?82:68}" font-family="Arial" font-size="${has('caratteri')?15:9}" fill="#345641">Sorella</text><rect x="191" y="${has('caratteri')?108:81}" width="${has('caratteri')?78:54}" height="${has('caratteri')?44:24}" rx="7" fill="#c6d7bb"/><path d="M206 126h30v18h-30Zm30 4 11-5v21l-11-5" fill="${has('caratteri')?'#436d55':'#889380'}"/>${has('scheda')?'<rect x="304" y="87" width="115" height="129" rx="7" fill="#fff9e7"/><g font-family="Arial" font-size="10" fill="#496047"><text x="314" y="111">1 · Apri i contatti</text><text x="314" y="140">2 · Scegli il nome</text><text x="314" y="169">3 · Videochiama</text></g>':''}<circle cx="85" cy="80" r="21" fill="#c29b79"/><path d="M53 140q32-69 64 0" fill="#8d9b80"/><text x="25" y="221" font-family="Arial" font-size="11" fill="#465e46">${has('caratteri')?'Comandi più leggibili':'Telefono da adattare'}</text>`;}
 else if(person?.id==='nico'){art=`<path d="M176 81q0-47 40-47t40 47" fill="none" stroke="#8d8264" stroke-width="10"/><rect x="153" y="67" width="128" height="157" rx="24" fill="#c1a280"/><rect x="174" y="139" width="86" height="64" rx="11" fill="#f3dfb8"/>${has('scomparti')?'<path d="M180 148v44m31-44v44m31-44v44" stroke="#99755d" stroke-width="3"/>':''}${has('sequenza')?'<g font-family="Arial" font-size="12" fill="#46614c"><rect x="316" y="61" width="96" height="39" rx="8" fill="#fbf4df"/><text x="326" y="85">1 · Quaderno</text><rect x="316" y="113" width="96" height="39" rx="8" fill="#fbf4df"/><text x="326" y="137">2 · Astuccio</text><rect x="316" y="165" width="96" height="39" rx="8" fill="#fbf4df"/><text x="326" y="189">3 · Chiudi</text></g>':''}<circle cx="66" cy="94" r="19" fill="#c49a74"/><path d="M38 153q28-67 56 0" fill="#8c9e7d"/>`;}
 else if(person?.id==='irene'){art=`<rect x="196" y="${has('piano')?110:72}" width="198" height="18" rx="4" fill="#b79775"/><path d="M207 ${has('piano')?128:90}v84m175 ${has('piano')?128:90}v84" stroke="#8a735b" stroke-width="7"/><circle cx="98" cy="90" r="19" fill="#c99c7a"/><path d="M96 113v45h46l26 29" stroke="#7c8c79" stroke-width="16" stroke-linecap="round" fill="none"/><circle cx="103" cy="186" r="31" fill="none" stroke="#536d62" stroke-width="6"/><circle cx="176" cy="207" r="7" fill="#536d62"/><path d="M${has('percorso')?'25 226h365':'280 222h87'}" stroke="#79986b" stroke-width="4" stroke-dasharray="7 5"/>${has('percorso')?'':'<rect x="36" y="205" width="37" height="26" rx="3" fill="#c7a572"/>'}<rect x="267" y="${has('piano')?78:40}" width="41" height="30" rx="5" fill="#7e8c85"/><circle cx="288" cy="${has('piano')?93:55}" r="9" fill="#ecdfc5"/>`;}
 else art='<path d="M90 173h256" stroke="#9aac87" stroke-width="5"/><circle cx="220" cy="86" r="30" fill="#c6a07e"/><path d="M167 167q53-114 106 0" fill="#899e80"/>';
 return svgWrap(art,'La persona e i sostegni scelti',supports.map(x=>x.label).join('. '));}
function storyArt(setting){return svgWrap(setting==='spazio'?`<circle cx="330" cy="65" r="37" fill="#b8b6bd"/><path d="M0 214Q167 95 440 190v55H0Z" fill="#d8cbbe"/><path d="M170 174v-39l62-55 63 55v39Z" fill="#a6b9b6"/><rect x="218" y="135" width="27" height="39" fill="#f8e6c6"/><circle cx="115" cy="137" r="13" fill="#ca9678"/><path d="M97 182q18-59 36 0" fill="#9c778f"/><circle cx="328" cy="151" r="13" fill="#c49c7b"/><path d="M310 196q18-59 36 0" fill="#6f8d76"/><g fill="#fbf6e5"><circle cx="64" cy="50" r="3"/><circle cx="187" cy="28" r="3"/><circle cx="398" cy="101" r="3"/></g>`:`<path d="M0 183Q160 175 440 198v47H0Z" fill="#bad0ba"/><path d="M95 210q114-147 239 0" stroke="#b1896e" stroke-width="24" fill="none"/><path d="M104 172h218" stroke="#bba276" stroke-width="10"/><circle cx="191" cy="163" r="10" fill="#8e6b98"/><circle cx="65" cy="104" r="13" fill="#ca9678"/><path d="M47 149q18-59 36 0" fill="#9c778f"/><circle cx="371" cy="110" r="13" fill="#c49c7b"/><path d="M353 155q18-59 36 0" fill="#6f8d76"/><circle cx="370" cy="38" r="21" fill="#dfb86d"/>`,'L’ambientazione della tua storia','Due personaggi, un progetto ancora da completare.');}
function serviceArt(service){return svgWrap(`<path d="M82 120l138-84 138 84v104H82Z" fill="#fbf2de"/><path d="M220 36l138 84H82Z" fill="#879a7f"/><rect x="190" y="144" width="59" height="80" rx="5" fill="#bba383"/><rect x="105" y="145" width="49" height="43" rx="5" fill="#a1b8a8"/><rect x="281" y="145" width="49" height="43" rx="5" fill="#a1b8a8"/><rect x="143" y="96" width="155" height="34" rx="8" fill="#f6e0b4"/><text x="220" y="118" text-anchor="middle" font-family="Arial" font-size="12" fill="#615039">${xml(service?.label||'Il tuo servizio')}</text><path d="M220 231v-36" stroke="#486e53" stroke-width="4"/><path d="M213 202l7-8 7 8" stroke="#486e53" stroke-width="3" fill="none"/>`,'Un servizio aperto alle persone','Un ingresso, attività organizzate e professionisti che collaborano.');}
function introArt(){return studioArt();}
function board(){const b=node('aside',null,'visual-board');b.setAttribute('aria-label','Il lavoro che stai costruendo');b.dataset.lab=LABS[journey().step-1]?.id;b.append(node('div',LAB_PRESENTATION[journey().step-1]?.product||'Il tuo lavoro','board-label'));b.append(node('p','Le tue scelte aggiornano questa anteprima.','board-help'));const canvas=node('div',null,'board-canvas');canvas.id='liveCanvas';b.append(canvas);return b;}
function intro(){const s=node('section',null,'intro'),c=node('div');c.append(node('p','Servizi per la sanità e l’assistenza sociale','eyebrow'),node('h1','Che cosa fa chi lavora con le persone?'),node('p','In questo indirizzo impari a comprendere la salute, costruire relazioni, sostenere l’autonomia e progettare attività e servizi.','lead'),node('p','Qui crei una scheda sulla salute, un incontro, un piano di sostegno, una storia e una proposta di servizio.'),btn('Inizia i laboratori →',e=>classUI.begin(e.currentTarget)),node('small','Puoi tornare indietro e riprendere da questo dispositivo.'));const art=node('div',null,'intro-visual');art.innerHTML=introArt();const caption=node('div','Cinque laboratori · cinque lavori personali','intro-caption');art.append(caption);s.append(c,art);mount.append(s);const route=node('div',null,'route-intro');const hints=['Corpo, patologie e bisogni di cura.','Domande, ascolto e partecipazione.','Desideri, strumenti e sostegni.','Una storia digitale, anche con l’IA.','Attività, professionisti e accesso.'];LABS.forEach((l,i)=>{const card=node('section',null,'route-card');card.style.setProperty('--accent',l.color);card.append(symbol(l.id),node('h2',l.label),node('p',hints[i]));route.append(card);});mount.append(route);}
function heading(){
 const j=journey(),lab=LABS[j.step-1],c=cursor(j),h=node('div',null,'stage-heading'),copy=node('div');
 copy.append(node('p',`Laboratorio ${j.step} di 5 · ${lab.label}`,'eyebrow'),node('h1',LAB_PRESENTATION[j.step-1].title),node('p',LAB_PRESENTATION[j.step-1].result,'stage-purpose'));
 h.append(copy,btn('Nota su questo punto',e=>openNotes(e.currentTarget),'plain-button'));mount.append(h);
 const phases=node('ol',null,'guide-progress');phases.setAttribute('aria-label',`Passaggi di ${lab.label}`);
 GUIDE[j.step-1].forEach((t,i)=>{const n=node('li',null,c===i?'active':'');n.append(node('b',`${i+1}.`),' ',node('span',t));n.dataset.position=i<c?'past':i===c?'current':'next';if(c===i)n.setAttribute('aria-current','step');phases.append(n);});mount.append(phases);
}
function optionalTitle(text,area,key){const d=node('details',null,'optional-title');d.append(node('summary',text+' · facoltativo'),field(text,area,key,65));return d;}
function guidedTask(left){
 const j=journey(),c=cursor(j);let s;
 if(j.step===1){const condition=CONDITIONS.find(x=>x.id===j.health.focus);
  if(c===0){s=sheet('Quale tema vuoi conoscere meglio?','Una patologia è una malattia o una condizione che cambia il funzionamento del corpo. Scegli un tema: vedrai come funziona e che cosa può cambiare.');s.append(choose(CONDITIONS.map(x=>({...x,detail:x.group})),'health','focus'));}
  else{s=sheet('Come lo spiegheresti a una famiglia?',condition?.question);s.append(node('p','Scegli una spiegazione. Se vuoi, cambiala nel riquadro sotto.','field-help'),exampleChoices(condition.examples,'health','explanation'),field('La spiegazione della tua scheda','health','explanation',230,true),optionalTitle('Titolo della scheda','health','title'));}
 }
 if(j.step===2){
  if(c===0){s=sheet('Sei tu ad aprire un incontro tra genitori.','Il facilitatore aiuta il gruppo ad ascoltarsi. Elena cerca aiuti per suo padre; Diego vuole comunicare meglio con sua figlia; Sonia preferisce ascoltare prima di parlare.');s.append(node('p','Quale domanda fai al gruppo?','request'),choose(OPENINGS.map(x=>({...x,detail:x.focus})),'relation','opening'));}
  if(c===1){s=sheet('Come le permetti di partecipare?');s.append(node('p','Sonia: «Mi interessa esserci, ma oggi non me la sento di parlare davanti a tutti.»','voice'),choose(PARTICIPATION,'relation','participation'));}
  if(c===2){s=sheet('Che cosa dici prima di salutarvi?','Scegli una frase che raccolga le richieste del gruppo. Puoi modificarla nel riquadro.');s.append(exampleChoices(['«Abbiamo raccolto richieste diverse. Al prossimo incontro decidiamo insieme quale riprendere.»','«Chi vuole può lasciare una domanda. Concordiamo come darle spazio nel prossimo incontro.»'],'relation','closing'),field('La tua frase di chiusura','relation','closing',160,true));}
 }
 if(j.step===3){const person=PERSONS.find(x=>x.id===j.autonomy.person);
  if(c===0){s=sheet('Con chi vuoi progettare un aiuto?','La cura parte da ciò che una persona desidera fare. Scegli una persona e ascolta il suo obiettivo.');s.append(choose(PERSONS.map(x=>({...x,label:`${x.name} · ${x.age}`,detail:x.goal})),'autonomy','person'));}
  if(c===1){s=sheet('Quali sostegni prepari?',person?.context);s.append(node('p','Puoi scegliere più sostegni. Guarda come cambia la proposta.','field-help'),choose(person.supports,'autonomy','supports',{check:true}));}
  if(c===2){s=sheet('Adesso ascolta la nuova richiesta.','Autonomia significa poter scegliere e fare con i sostegni necessari. L’aiuto può cambiare.');s.append(node('p',person.request,'voice'),choose(person.adaptations,'autonomy','adaptation'));}
 }
 if(j.step===4){const goal=GOALS.find(x=>x.id===j.creative.goal),setting=SETTINGS.find(x=>x.id===j.creative.setting);
  if(c===0){s=sheet('Che cosa vuoi far sperimentare ai bambini?','Creerai una storia digitale per bambini di 6–8 anni. Scegli il suo scopo educativo: ciò che il gioco li aiuterà a sperimentare.');s.append(choose(GOALS,'creative','goal'));}
  if(c===1){s=sheet('Dove comincia la tua storia?');s.append(choose(SETTINGS.map(x=>({...x,detail:x.start})),'creative','setting'));}
  if(c===2){s=sheet('La bozza fa fare tutto all’adulto. Cambiala.','Questa bozza è stata preparata con IA per il laboratorio. Sei tu a decidere come migliorarla.');s.append(node('p',setting.draft,'voice'),node('p','Scegli un seguito in cui i bambini possano intervenire. Puoi modificarlo nel riquadro.','field-help'),exampleChoices(goal.endings,'creative','ending'),field('Il seguito per «'+goal.options[storyBranch(j)]+'»','creative','ending',230,true),optionalTitle('Titolo della storia','creative','title'));}
 }
 if(j.step===5){const service=SERVICES.find(x=>x.id===j.service.kind);
  if(c===0){s=sheet('Quale bisogno vuoi affrontare?','Un servizio organizza persone, attività e risorse per rispondere a un bisogno. Un centro diurno, per esempio, offre assistenza e attività durante la giornata.');s.append(choose(SERVICES.map(x=>({...x,detail:x.need})),'service','kind'));}
  if(c===1){s=sheet('Che cosa offrirà il servizio?',service?.team);s.append(choose(service.activities,'service','activity'));}
  if(c===2){s=sheet('Due persone non riescono a prenotare.','Il tuo servizio accetta solo prenotazioni online, a un orario fisso. Come cambi l’accesso?');s.append(node('p','«Non riesco a prenotare su internet.»\n«A quell’ora lavoro: possiamo concordare un altro momento?»','voice'),choose(ACCESS,'service','access'));}
  if(c===3){s=sheet('Come capirai se il servizio funziona?','La valutazione serve a raccogliere informazioni per migliorare. Scegli che cosa osservare.');s.append(choose(CHECKS,'service','check'),optionalTitle('Nome del servizio','service','name'));}
 }
 left.append(s);
}
function voiceReply(text){const card=node('blockquote',null,'voice-card'),colon=text.indexOf(':');if(colon>0&&colon<25){card.append(node('strong',text.slice(0,colon),'speaker'),node('p',text.slice(colon+1).trim()));}else card.append(node('p',text));return card;}
function productPart(title,text){const card=node('section',null,'product-part');card.append(node('h3',title),node('p',text));return card;}
function updateLive(){
 const canvas=$('liveCanvas');if(canvas){canvas.replaceChildren();const j=journey(),c=cursor(j),art=node('div',null,'product-art');canvas.dataset.lab=LABS[j.step-1]?.id;
 if(j.step===1){const item=CONDITIONS.find(x=>x.id===j.health.focus);
  if(!item){art.innerHTML=conditionDiagram('asma',false);canvas.append(art,node('h2','Quale tema metterai nella tua scheda?'),node('p','Scegli un tema per vedere il disegno e le informazioni.','empty-preview'));}
  else if(c===0){canvas.append(node('p',item.group,'product-kicker'),node('h2',item.label));const comparison=node('div',null,'health-comparison');for(const [title,text,changed] of [['Come funziona',item.normal,false],['Che cosa cambia',item.change,true]]){const part=node('section'),drawing=node('div');drawing.innerHTML=conditionDiagram(item.id,changed);part.append(node('h3',title),drawing,node('p',text));comparison.append(part);}canvas.append(comparison);}
  else{canvas.append(node('p',item.group,'product-kicker'),node('h2',j.health.title||item.label));art.innerHTML=conditionDiagram(item.id,true);canvas.append(art,productPart('La tua spiegazione',j.health.explanation||'Scegli una spiegazione o scrivila nel riquadro: entrerà nella scheda.'));}
  if(item){const d=node('details',null,'more-info');d.append(node('summary','Cure e sostegni'),node('p',item.care));canvas.append(d);}canvas.append(node('p','Disegni schematici: non sono esami clinici.','diagram-legend'));
 }
 if(j.step===2){art.innerHTML=roomArt();canvas.append(art);const opening=OPENINGS.find(x=>x.id===j.relation.opening),participation=PARTICIPATION.find(x=>x.id===j.relation.participation);canvas.append(node('h2',c===0?'Le voci del gruppo':c===1?'La risposta di Sonia':'La tua proposta di incontro'));
  if(c===0){if(opening)opening.replies.forEach(t=>canvas.append(voiceReply(t)));else canvas.append(node('p','Scegli la domanda di apertura: ascolterai tre risposte diverse.','empty-preview'));}
  else if(c===1)canvas.append(voiceReply(participation?'Sonia: '+participation.reply:'Sonia: scegli come permettermi di partecipare. Qui vedrai la mia risposta.'));
  else{canvas.append(productPart('Per aprire',opening?.label||''),productPart('Per partecipare',participation?.label||''),productPart('Per chiudere',j.relation.closing||'La frase che scegli entrerà qui.'));}
 }
 if(j.step===3){const person=PERSONS.find(x=>x.id===j.autonomy.person),supports=person?.supports.filter(s=>j.autonomy.supports.includes(s.id))||[];art.innerHTML=supportArt(person,supports);canvas.append(art,node('h2',person?`Il piano per ${person.name}`:'Da quale desiderio partirai?'));if(person)canvas.append(productPart('Che cosa vuole fare',person.goal));else canvas.append(node('p','Scegli una persona per scoprire il suo obiettivo.','empty-preview'));if(supports.length){const chosen=node('div',null,'support-list');supports.forEach(x=>chosen.append(node('p',x.label,'result-line')));canvas.append(chosen);}else if(person&&c>0)canvas.append(node('p','I sostegni che scegli appariranno nel disegno e nel piano.','empty-preview'));const a=person?.adaptations.find(x=>x.id===j.autonomy.adaptation);if(a&&c===2)canvas.append(productPart('Come adatti l’aiuto',a.detail));
 }
 if(j.step===4){const setting=SETTINGS.find(x=>x.id===j.creative.setting),goal=GOALS.find(x=>x.id===j.creative.goal);art.innerHTML=storyArt(setting?.id);canvas.append(art,node('h2',j.creative.title||setting?.label||'La tua storia digitale'));if(goal)canvas.append(node('p','Scopo educativo: '+goal.label,'board-pill'));else canvas.append(node('p','Scegli che cosa vuoi far sperimentare ai bambini.','empty-preview'));if(setting)canvas.append(node('p',setting.start,'story-start'));if(c===2&&j.creative.ending){canvas.append(node('p',j.creative.ending,'story-personal'));const reader=node('section',null,'story-reader');reader.append(node('h3','Provala come lettore'),node('p',goal.question));const controls=node('div',null,'story-controls'),outcome=node('p','Scegli una risposta per aprire il seguito.','story-outcome');outcome.setAttribute('role','status');goal.options.forEach((t,i)=>controls.append(btn(t,()=>{outcome.textContent=i===storyBranch(j)?j.creative.ending:goal.endings[i];},'')));reader.append(controls,outcome);canvas.append(reader);}
 }
 if(j.step===5){const service=SERVICES.find(x=>x.id===j.service.kind),activity=service?.activities.find(x=>x.id===j.service.activity),access=ACCESS.find(x=>x.id===j.service.access),check=CHECKS.find(x=>x.id===j.service.check);art.innerHTML=serviceArt(service);canvas.append(art,node('h2',j.service.name||service?.label||'La tua proposta di servizio'));if(service){canvas.append(productPart('Il bisogno',service.need));if(c>=1)canvas.append(productPart('Chi collabora',service.team));}else canvas.append(node('p','Scegli un bisogno per iniziare a costruire il servizio.','empty-preview'));if(activity)canvas.append(productPart('L’attività',activity.label));if(access&&c>=2)canvas.append(productPart('L’accesso',access.detail));if(check&&c===3)canvas.append(productPart('Che cosa osserverai',check.detail));
 }
 }
 if($('downloadProject'))$('downloadProject').href=jsonHref();if($('downloadPortfolio'))$('downloadPortfolio').href=svgHref();if($('backupBeforeReset'))$('backupBeforeReset').href=jsonHref();
}
function updateHelp(error=false){const box=$('requirements');if(!box)return;box.replaceChildren();const pending=guideIssues(journey());box.hidden=!pending.length;box.dataset.error=String(error&&!!pending.length);if(pending.length)box.append(node('p',pending[0].text));const next=$('continue');if(next)next.disabled=journey().step===6&&journey().finished||pending.length>0;}
function go(step,part=0,action=null){const j=journey();j.step=step;j.part=part;j.guideVersion=1;j.guideCursor=action??(step>=1&&step<=5&&part?GUIDE[step-1].length-1:0);j.visited=Math.max(j.visited,step);clock++;state.dirty=true;keep();schedule();render(true);}
function advance(){const j=journey(),c=cursor(j),pending=guideIssues(j,c);if(pending.length){updateHelp(true);const target=$(pending[0].id);target?.scrollIntoView({block:'center',behavior:'instant'});(target?.matches('input,textarea,button')?target:target?.querySelector('input,button'))?.focus({preventScroll:true});return;}
 if(j.step===6){j.finished=true;j.attestato={...j.attestato,id:crypto.randomUUID(),date:new Date().toISOString()};changed(true,true);$('completion')?.querySelector('h2')?.focus();$('completion')?.scrollIntoView({block:'center',behavior:'instant'});return;}
 if(c<GUIDE[j.step-1].length-1){beginRevision(j);go(j.step,1,c+1);}
 else{titleDefaults(j);const id=LABS[j.step-1].id;if(!j.done.includes(id))j.done.push(id);go(j.step+1,0);}
}
function footer(){const j=journey(),c=cursor(j),help=node('div',null,'requirements');help.id='requirements';help.hidden=true;help.setAttribute('role','status');mount.append(help);const actions=node('div',null,'stage-footer');actions.append(btn('Indietro',()=>{if(j.step===6)go(5,1);else if(c>0)go(j.step,1,c-1);else go(j.step-1,j.step>1?1:0);},'secondary'));
 const next=btn(j.step===6?(j.finished?'Percorso concluso ✓':'Concludi il percorso'):c<GUIDE[j.step-1].length-1?GUIDE[j.step-1][c+1]+' →':j.step===5?'Raccogli i tuoi lavori →':'Continua con '+LABS[j.step].label+' →',advance);next.id='continue';next.disabled=j.step===6&&j.finished||guideIssues(j).length>0;actions.append(next);if(j.step===6)$('summaryNextActions').append(help,actions);else mount.append(actions);}
function interests(){const box=node('div',null,'choices interest-choices');LABS.forEach(l=>{const input=node('input');input.type='checkbox';input.name='ssas-interests';input.id=`interest-${l.id}`;input.value=l.id;input.checked=journey().interests.includes(l.id);input.addEventListener('change',()=>{const j=journey();j.interests=input.checked?[...j.interests,l.id]:j.interests.filter(id=>id!==l.id);changed(false);});const lab=node('label',null,'choice');lab.append(input,node('strong',l.label));box.append(lab);});return box;}
function summary(){const j=journey(),h=node('section',null,'summary-head');h.append(node('p','Cinque laboratori · il tuo percorso','eyebrow'),node('h1','Ecco che cosa hai creato.'),node('p','Una scheda sulla salute, una proposta di incontro, un piano di sostegno, una storia e un servizio.'));mount.append(h);const portfolio=node('section',null,'portfolio');portfolio.setAttribute('aria-label','I tuoi cinque lavori');const items=summaryItems(j);items.forEach((item,i)=>{const l=LABS[i],card=node('article');card.append(node('p',l.label,'eyebrow'));const detail=node('details',null,'portfolio-detail'),entry=node('summary');entry.append(node('h2',item.title),node('p',item.text));const body=node('div',null,'portfolio-body');body.append(node('p',item.detail));detail.append(entry,body);card.append(detail);const subject=node('details',null,'subject');subject.append(node('summary','Materie di indirizzo'),node('strong',l.subject),node('p',l.bridge));body.append(subject,btn('Rivedi questo lavoro',()=>go(i+1,1),'secondary'));portfolio.append(card);});mount.append(portfolio);const reflect=sheet('Che cosa vorresti approfondire?','Puoi indicare più parti, anche tutte.');reflect.append(interests());const field=node('textarea');field.id='nextIdea';field.name='ssas-next-idea';field.maxLength=180;field.rows=2;field.value=j.nextIdea;field.addEventListener('input',()=>{j.nextIdea=field.value;changed(false);});reflect.append(label('Una tua idea da continuare · facoltativo',field));const nextSlot=node('div');nextSlot.id='summaryNextActions';reflect.append(nextSlot);h.after(reflect);const actions=node('div',null,'actions');actions.append(btn('Nota sul percorso',e=>openNotes(e.currentTarget),'plain-button'));mount.append(actions);
 if(j.finished){const done=node('section',null,'complete');done.id='completion';const title=node('h2','Hai attraversato tutti e cinque i laboratori.');title.tabIndex=-1;done.append(title,node('p',`Vorresti approfondire: ${LABS.filter(l=>j.interests.includes(l.id)).map(l=>l.label.toLowerCase()).join(', ')}.`));if(j.nextIdea.trim())done.append(node('p',j.nextIdea));done.append(node('p','Porta uno dei tuoi lavori all’incontro con studenti e docenti: sarà un punto da cui fare domande.'));done.append(btn('Apri il tuo attestato',e=>certificateUI.open(e.currentTarget),'primary'));const link=node('a','Esplora l’indirizzo SSAS →','secondary');link.href='https://spaziodocentimeuccimattei.github.io/indirizzi.html#ssas';done.append(link);reflect.after(done);}}
function render(focus=true){const focused=document.activeElement?.id,j=journey();nav.replaceChildren();mount.replaceChildren();const lab=LABS[j.step-1];document.documentElement.style.setProperty('--accent',lab?.color||'#a44844');if(j.step===0)intro();else{LABS.forEach((l,i)=>{const b=btn('',()=>go(i+1,0),'');const done=j.done.includes(l.id);b.append(node('span',done?'✓':String(i+1),'nav-number'),node('span',l.label));b.disabled=i+1>j.visited;if(j.step===i+1)b.setAttribute('aria-current','step');b.setAttribute('aria-label',`${l.label}${done?' · completato':''}`);nav.append(b);});if(j.step===6)summary();else{heading();const grid=node('div',null,'workspace-grid'),left=node('div');guidedTask(left);grid.append(left,board());mount.append(grid);}footer();}updateLive();updateHelp();renderNotes();const headingTarget=mount.querySelector('h1');if(headingTarget)headingTarget.tabIndex=-1;if(focus){const title=headingTarget;title.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}else if(focused)$(focused)?.focus({preventScroll:true});}
function context(){const j=journey();return `SSAS · cinque laboratori · ${j.step===0?'Ingresso':j.step===6?'Raccolta e curiosità':`${LABS[j.step-1].label} · ${GUIDE[j.step-1][cursor(j)]}`}`;}
function exportedProject(){return {experience:FORMAT,participant:state.participant,project:state.project,notes:state.notes.map(({pending,...n})=>n)};}
function jsonHref(){return fileURL(JSON.stringify(exportedProject(),null,2),'application/json;charset=utf-8');}
function wrap(s,max=70){const rows=[];let line='';for(const word of String(s).split(/\s+/)){if(word.length>max){if(line){rows.push(line);line='';}for(let i=0;i<word.length;i+=max)rows.push(word.slice(i,i+max));continue;}if(line.length+word.length+1>max){rows.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)rows.push(line);return rows;}
function collectionSVG(){const j=journey(),items=summaryItems(j),cardHeights=items.map(x=>95+(wrap(x.title,40).length-1)*25+wrap(x.text,68).length*21+wrap(x.detail,75).length*18);let y=160;const cards=items.map((x,i)=>{const l=LABS[i],top=y;y+=cardHeights[i]+18;let ty=top+61;const title=wrap(x.title,40).map(t=>{const v=`<text x="54" y="${ty}" font-size="21" font-weight="700">${xml(t)}</text>`;ty+=25;return v;}).join('');const body=wrap(x.text,68).map(t=>{const v=`<text x="54" y="${ty+3}" font-size="15">${xml(t)}</text>`;ty+=21;return v;}).join('');const detail=wrap(x.detail,75).map(t=>{const v=`<text x="54" y="${ty+4}" font-size="12" fill="#596452">${xml(t)}</text>`;ty+=18;return v;}).join('');return `<rect x="30" y="${top}" width="700" height="${cardHeights[i]}" rx="15" fill="#fffdf4" stroke="#cbd6c3"/><text x="54" y="${top+28}" font-size="11" font-weight="700" fill="${l.color}">${xml(l.label)}</text>${title}${body}${detail}`;}).join('');const reflection=wrap(`Vorrei approfondire: ${LABS.filter(l=>j.interests.includes(l.id)).map(l=>l.label.toLowerCase()).join(', ')||'da scegliere'}. ${j.nextIdea}`,72);const height=y+reflection.length*20+90;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 ${height}" role="img" aria-labelledby="title desc"><title id="title">I miei cinque laboratori SSAS</title><desc id="desc">I cinque lavori e le curiosità dichiarate nel percorso.</desc><rect width="760" height="${height}" fill="#f2f1e5"/><g font-family="Arial,sans-serif" fill="#294538"><text x="34" y="42" font-size="12">Bussola · IIS Meucci - Mattei | Decimomannu</text><text x="34" y="94" font-size="31" font-weight="700">I miei cinque laboratori SSAS</text><text x="34" y="126" font-size="13">Salute · Relazione · Cura e autonomia · Creatività · Progettazione</text>${cards}${reflection.map((t,i)=>`<text x="34" y="${y+27+i*20}" font-size="14">${xml(t)}</text>`).join('')}<text x="34" y="${height-23}" font-size="11">Il mio percorso di esplorazione · Situazioni e personaggi immaginari</text></g></svg>`;}
function svgHref(){return fileURL(collectionSVG(),'image/svg+xml;charset=utf-8');}
document.addEventListener('click',async event=>{const a=event.target.closest?.('a[download]');if(!a||!['downloadPortfolio','downloadProject','backupBeforeReset'].includes(a.id)||!['localhost','127.0.0.1'].includes(location.hostname))return;if(a.dataset.ready==='true'){delete a.dataset.ready;return;}event.preventDefault();try{const kind=a.id==='downloadPortfolio'?'svg':'json';const r=await fetch('/__bussola/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,content:kind==='svg'?collectionSVG():JSON.stringify(exportedProject(),null,2)})});if(!r.ok)throw new Error();a.href=(await r.json()).url;a.dataset.ready='true';a.click();}catch{a.href=a.id==='downloadPortfolio'?svgHref():jsonHref();a.dataset.ready='true';a.click();}});
function renderNotes(){const pending=state.notes.filter(n=>n.pending).length;$('noteCount').textContent=String(state.notes.length);const list=$('notesList');list.replaceChildren();if(!state.notes.length)list.append(node('p','Qui ritroverai ogni nota con il punto del percorso a cui si riferisce.','field-help'));for(const n of state.notes){const entry=node('article',null,'note-entry');entry.append(node('div',`${n.contesto} · ${n.ruolo_dichiarato==='docente'?'Prova docente':'Prova alunno'}`,'note-meta'),node('p',n.testo),node('div',n.pending?'Conservata sul dispositivo · da inviare':localTest?'Salvata nel database di prova':'Salvata online','note-sync'));list.append(entry);}if(notesDialog.open&&pending)$('noteStatus').textContent='La nota è sul dispositivo. Il salvataggio online è in corso o da riprovare.';else if(notesDialog.open&&state.notes.length)$('noteStatus').textContent='Le tue note sono salvate, ciascuna separatamente.';}
function draftFromForm(){return {text:$('noteText').value,role:$('noteRole').value,type:$('noteType').value,context:$('noteContext').value,step:state.draft?.step??noteStep()};}
function openNotes(trigger){noteTrigger=trigger;const d=state.draft?.text?.trim()?state.draft:{text:'',role:state.draft?.role||'alunno',type:state.draft?.type||'chiarezza',context:context(),step:noteStep()};state.draft=d;keep();$('noteContext').value=d.context;$('noteRole').value=d.role;$('noteType').value=d.type;$('noteText').value=d.text;$('noteStatus').textContent='';renderNotes();notesDialog.showModal();$('noteText').focus();}
for(const id of ['noteText','noteRole','noteType'])$(id).addEventListener('input',()=>{state.draft=draftFromForm();keep();});
$('noteForm').addEventListener('submit',event=>{event.preventDefault();const draft=draftFromForm(),text=draft.text.trim();if(text.length<2)return;const n={id:crypto.randomUUID(),passaggio:draft.step,contesto:draft.context,versione:1,ruolo_dichiarato:draft.role,tipo:draft.type,testo:text,created_at:new Date().toISOString(),pending:true};state.notes.push(n);state.draft=null;$('noteText').value='';$('noteContext').value=context();state.draft={text:'',role:draft.role,type:draft.type,context:context(),step:noteStep()};keep();renderNotes();updateLive();sync();});
$('openNotes').addEventListener('click',e=>openNotes(e.currentTarget));$('closeNotes').addEventListener('click',()=>notesDialog.close());notesDialog.addEventListener('close',()=>{state.draft=draftFromForm();keep();noteTrigger?.focus({preventScroll:true});});
retry.addEventListener('click',()=>sync());window.addEventListener('online',()=>sync());
$('newProject').addEventListener('click',()=>{$('backupBeforeReset').href=jsonHref();$('resetDialog').showModal();});$('cancelReset').addEventListener('click',()=>$('resetDialog').close());$('confirmReset').addEventListener('click',()=>{try{localStorage.setItem(KEY+':archivio:'+crypto.randomUUID(),JSON.stringify(state));}catch{status('Non riesco a conservare il percorso precedente. Scarica una copia prima di iniziarne uno nuovo.',true);return;}epoch++;clearTimeout(timer);connected=false;conflict=false;state={project:freshProject(),token:'',participant:'',revision:0,dirty:false,notes:[],draft:null};keep();$('resetDialog').close();document.dispatchEvent(new CustomEvent('bussola-progetto-nuovo'));status('Un progetto nuovo, con un identificativo distinto.');render(true);});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')keep();});
const classUI=setupClass({key:KEY,isIntro:()=>journey().step===0,start:()=>go(1,0),token:()=>state.token,ensure:async()=>{if(!connected)await connect();if(!state.participant)throw new Error('Il collegamento non è riuscito. Riprova tra poco.');}});
const certificateUI=setupParticipantCertificate({project:()=>state.project,participant:()=>state.participant,revision:()=>state.revision,identity:()=>classUI.identity(),save:()=>changed(false,true)});
if(localTest)document.querySelector('.preview-strip').textContent='Prova locale · Dati fittizi · SSAS';
render(false);if(state.token)sync();
