export const FORMAT='bussola-sia-proposta-1';
export const STORE='bussola.sia.anteprima.v1';
export const LABS=[
 {id:'processi',label:'Processi',product:'Una mappa del lavoro',client:'Officina Ripresa',subjects:'Economia aziendale · Informatica'},
 {id:'dati',label:'Dati',product:'Un archivio che risponde',client:'Officina Ripresa',subjects:'Informatica · Economia aziendale · Matematica'},
 {id:'programma',label:'Programmazione',product:'Una regola che agisce',client:'Spazio Mix',subjects:'Informatica · Matematica · Economia aziendale'},
 {id:'interfaccia',label:'Interfacce',product:'Una schermata da usare',client:'Spazio Mix',subjects:'Informatica · Economia aziendale · Comunicazione e inglese'},
 {id:'accessi',label:'Accessi e responsabilità',product:'Permessi messi alla prova',client:'Officina Ripresa',subjects:'Informatica · Diritto · Economia aziendale'}
];
export const STAGES=[
 ['Una data promessa troppo presto?','Officina Ripresa rimette in uso cuffie e controller. Prima di promettere una consegna, deve organizzare il lavoro. Riordina i tre passaggi con le frecce, poi premi «Prova il processo».','Prova il processo per vedere che cosa succede.','Passa le informazioni'],
 ['Passa le informazioni, non il problema.','Il tecnico deve sapere che cosa fare sul controller R02. Scegli quali informazioni passargli, poi prova lo scambio.','Scegli una scheda e prova lo scambio.','Apri l’archivio'],
 ['Che cosa vuoi sapere degli interventi?','Costruisci l’archivio di Officina Ripresa. Aggiungi colonne: la tabella prende forma accanto a te. Per cercare le consegne ti serviranno stato e giorno.','Aggiungi almeno una colonna all’archivio.','Fai una ricerca'],
 ['L’archivio ti risponde davvero?','R02 compare due volte: è lo stesso intervento. Unisci le due schede, completa il giorno di R04 e cerca le consegne pronte.','Unisci il duplicato, scegli il giorno e aggiungi stato e giorno se mancano.','Passa al programma'],
 ['C’è posto per una prenotazione?','Un nuovo cliente: Spazio Mix organizza attività creative. Aggiungi tre blocchi e scegli una regola per le prenotazioni.','Aggiungi tutti e tre i blocchi.','Metti in esecuzione'],
 ['Il tuo programma, in azione.','Prova la regola con due posti e con zero posti disponibili. Osserva il risultato. Puoi cambiare i blocchi e riprovare: ogni prova riparte dai dati che leggi.','Esegui entrambe le prove con la regola attuale.','Disegna la schermata'],
 ['Disegna una schermata che si capisce.','Per Spazio Mix, componi la schermata: sposta i tre elementi, scegli uno stile e dai un nome al comando. Il tuo programma è già collegato.','Puoi usare i testi proposti o personalizzarli.','Usala come un visitatore'],
 ['Ora la tua idea si può usare.','Nella schermata a fianco scegli un’attività e quanti posti chiedere. Premi il tuo pulsante: si esegue il programma che hai costruito.','Fai almeno una prenotazione di prova.','Torna a Officina Ripresa'],
 ['Dai a ciascuno il suo spazio.','Si torna all’archivio di Officina Ripresa. Un permesso stabilisce che cosa si può vedere o cambiare. Modifica la bozza: chi può cambiare l’importo concordato?','Puoi modificare i permessi o conservare la bozza.','Prova i permessi'],
 ['Chi può cambiare il prezzo?','Prova come cliente e come accoglienza: tenta di cambiare l’importo. Poi puoi modificare i permessi e riprovare.','Prova entrambi i ruoli con i permessi attuali.','Raccogli le tue soluzioni']
];
export const PROCESS=[
 {id:'richiesta',label:'Raccogli la richiesta',role:'Accoglienza',text:'Oggetto, problema e data desiderata.'},
 {id:'risorse',label:'Verifica le risorse',role:'Tecnico',text:'Ricambi disponibili e lavoro già previsto.'},
 {id:'conferma',label:'Conferma la data',role:'Accoglienza',text:'La data viene comunicata al cliente.'}
];
export const FIELDS=[{id:'status',label:'Stato',why:'Distinguere pronto e in lavorazione.'},{id:'day',label:'Giorno',why:'Sapere per quando è previsto il lavoro.'},{id:'price',label:'Importo',why:'Vedere il prezzo concordato con il cliente.'}];
export const RECORDS=[
 {id:'R01',object:'Cuffie',status:'Pronto',day:'Venerdì',price:18},
 {id:'R02',object:'Controller',status:'In lavorazione',day:'Venerdì',price:25},
 {id:'R03',object:'Cassa audio',status:'Pronto',day:'Lunedì',price:20},
 {id:'R04',object:'Cuffie',status:'Pronto',day:null,price:15},
 {id:'R02',object:'Controller',status:'In lavorazione',day:'Venerdì',price:25}
];
export const BLOCKS=[{id:'leggi',label:'Leggi i dati',desc:'Richiesta e posti disponibili.'},{id:'controlla',label:'Controlla i posti',desc:'La condizione può essere vera o falsa.'},{id:'rispondi',label:'Rispondi',desc:'Conferma oppure metti in attesa.'}];
export const CASES=[{id:'libero',label:'Due posti disponibili',available:2,requested:1},{id:'pieno',label:'Zero posti disponibili',available:0,requested:1},{id:'ultimo',label:'L’ultimo posto',available:1,requested:1}];
export const PARTS=[{id:'scheda',label:'Scheda dell’attività'},{id:'posti',label:'Posti da richiedere'},{id:'azione',label:'Comando e risultato'}];
export const ROLES=[{id:'cliente',label:'Cliente',desc:'Vede solo il proprio intervento R01.'},{id:'tecnico',label:'Tecnico',desc:'Segue la lavorazione.'},{id:'accoglienza',label:'Accoglienza',desc:'Concorda e conferma gli importi.'}];
export const find=(a,id)=>a.find(x=>x.id===id);
export const clone=p=>JSON.parse(JSON.stringify(p));
export function createProject(id=crypto.randomUUID()){return {format:FORMAT,version:1,course:'sia',id,started:false,identity:null,screen:-1,unlocked:0,done:[],notes:[],interests:[],revision:0,updatedAt:null,title:'Le mie soluzioni digitali',process:{order:['richiesta','conferma','risorse'],handoff:null,runs:[],handoffRuns:[]},data:{fields:[],merged:false,missingDay:null,filter:'Venerdì',searched:false},program:{blocks:[],condition:'almeno',yes:'conferma',no:'attesa',runs:[]},ui:{order:['scheda','posti','azione'],style:'viola',title:'Crea con Spazio Mix',button:'Prenota un posto',runs:[]},access:{permissions:{cliente:{view:true,edit:true},tecnico:{view:true,edit:true},accoglienza:{view:true,edit:true}},runs:[]}};}
export function move(a,id,delta){const i=a.indexOf(id),j=i+delta;if(i<0||j<0||j>=a.length)return false;[a[i],a[j]]=[a[j],a[i]];return true;}
export function processSignature(p){return JSON.stringify(p.process.order);}
export function processRun(p){let request=false,verified=false,warning=false;const trace=[];for(const id of p.process.order){if(id==='richiesta'){request=true;trace.push({label:'Richiesta letta',text:'Controller R02: un tasto non risponde. Il cliente chiede venerdì.'});}if(id==='risorse'){verified=request;if(!request)warning=true;trace.push({label:request?'Risorse verificate':'Manca ancora la richiesta',text:request?'Il ricambio arriva lunedì. Venerdì non è ancora confermabile.':'Il tecnico non sa ancora quale ricambio controllare.'});}if(id==='conferma'){const safe=request&&verified;warning ||= !safe;trace.push({label:safe?'Una data verificata':'Una promessa da verificare',text:safe?'Si propone lunedì e si chiede conferma al cliente.':'Si promette venerdì prima di sapere se il lavoro è possibile.'});}}const r={id:crypto.randomUUID(),signature:processSignature(p),trace,warning,at:new Date().toISOString()};p.process.runs.push(r);return r;}
export function handoffRun(p){const rich=p.process.handoff==='completa';const r={id:crypto.randomUUID(),signature:p.process.handoff,at:new Date().toISOString(),text:rich?'Il tecnico legge: R02, controller, tasto bloccato, ricambio previsto lunedì. Può preparare il lavoro.':'Il tecnico legge R02 e controller, ma non il problema. Prima di preparare il lavoro chiede un chiarimento all’accoglienza.'};p.process.handoffRuns.push(r);return r;}
export function records(p){const list=p.data.merged?RECORDS.filter((_,i)=>i!==4):RECORDS;return list.map(r=>({...r,day:r.id==='R04'?p.data.missingDay:r.day}));}
export function query(p){const known=p.data.fields.includes('status')&&p.data.fields.includes('day');if(!known)return {known:false,rows:[],count:null,total:null};const rows=records(p).filter(r=>r.status==='Pronto'&&r.day===p.data.filter);return {known:true,rows,count:rows.length,total:p.data.fields.includes('price')?rows.reduce((s,r)=>s+r.price,0):null};}
export function programSignature(p){const c=p.program;return JSON.stringify([c.blocks,c.condition,c.yes,c.no]);}
export function execute(p,input){let read=false,check=null,output=null,remaining=input.available;const trace=[];for(const id of p.program.blocks){if(id==='leggi'){read=true;trace.push({label:'INPUT · dati in ingresso',text:`${input.available} ${input.available===1?'posto disponibile':'posti disponibili'}; ${input.requested} ${input.requested===1?'posto richiesto':'posti richiesti'}.`});}if(id==='controlla'){if(!read){trace.push({label:'Il controllo si ferma',text:'I dati non sono ancora stati letti. Sposta «Leggi i dati» prima del controllo.'});return {trace,output:'problema',remaining,problem:true};}check=p.program.condition==='almeno'?input.available>=input.requested:input.available>input.requested;trace.push({label:`CONDIZIONE · ${check?'vera':'falsa'}`,text:`${input.available} ${p.program.condition==='almeno'?'≥':'>'} ${input.requested}`});}if(id==='rispondi'){if(check===null){trace.push({label:'La risposta si ferma',text:'Manca il controllo dei posti: il programma non sa quale ramo usare.'});return {trace,output:'problema',remaining,problem:true};}output=check?p.program.yes:p.program.no;remaining=output==='conferma'?input.available-input.requested:input.available;trace.push({label:'OUTPUT · risultato',text:output==='conferma'?`Prenotazione confermata. ${remaining===1?'Resta 1 posto':`Restano ${remaining} posti`}.`:'Richiesta in lista di attesa. Nessun posto viene occupato.'});}}
 const problem=output===null||remaining<0;if(remaining<0)trace.push({label:'Una conferma senza posto',text:'Hai confermato anche quando i posti erano esauriti. Rivedi il ramo usato quando la condizione è falsa.'});return {trace,output:output||'problema',remaining,problem};}
export function runProgram(p,id){const c=find(CASES,id);if(!c)return null;const r={id:crypto.randomUUID(),caseId:id,signature:programSignature(p),input:{available:c.available,requested:c.requested},...execute(p,c),at:new Date().toISOString()};p.program.runs.push(r);return r;}
export function uiSignature(p){return JSON.stringify([programSignature(p),p.ui.order,p.ui.title,p.ui.button,p.ui.style]);}
export function runUI(p,activity,requested){const available=activity==='foto'?1:2;const input={available,requested:Number(requested)};const r={id:crypto.randomUUID(),signature:uiSignature(p),activity,input,...execute(p,input),at:new Date().toISOString()};p.ui.runs.push(r);return r;}
export function accessSignature(p){return JSON.stringify(p.access.permissions);}
export function runAccess(p,role,price){if(!find(ROLES,role)||!Number.isFinite(price)||price<0||price>100)return null;const perm=p.access.permissions[role];const r={id:crypto.randomUUID(),signature:accessSignature(p),role,requested:price,before:18,after:perm.edit?price:18,allowed:perm.edit,visible:perm.view,at:new Date().toISOString()};p.access.runs.push(r);return r;}
export function currentRuns(list,signature){return list.filter(r=>r.signature===signature);}
export function ready(p,s=p.screen){if(!p.started)return false;const c=p.data;return [currentRuns(p.process.runs,processSignature(p)).length>0,['completa','essenziale'].includes(p.process.handoff)&&currentRuns(p.process.handoffRuns,p.process.handoff).length>0,c.fields.length>0,c.merged&&!!c.missingDay&&c.fields.includes('status')&&c.fields.includes('day')&&c.searched,new Set(p.program.blocks).size===3,['libero','pieno'].every(id=>currentRuns(p.program.runs,programSignature(p)).some(r=>r.caseId===id)),p.ui.order.length===3&&!!p.ui.title.trim()&&!!p.ui.button.trim(),currentRuns(p.ui.runs,uiSignature(p)).length>0,ROLES.every(r=>typeof p.access.permissions[r.id]?.edit==='boolean'),['cliente','accoglienza'].every(id=>currentRuns(p.access.runs,accessSignature(p)).some(r=>r.role===id))][s]||false;}
export function completed(p){return p.started&&Array.from({length:10},(_,i)=>ready(p,i)&&p.done.includes(i)).every(Boolean);}
export function advance(p){if(!ready(p))return false;if(!p.done.includes(p.screen))p.done.push(p.screen);p.screen=Math.min(10,p.screen+1);p.unlocked=Math.max(p.screen,p.unlocked);return true;}
export function invalidate(p,lab){const stages=lab===2?[4,5,7]:[lab*2,lab*2+1];p.done=p.done.filter(s=>!stages.includes(s)||ready(p,s));return p;}
export function context(p){const n=p.screen;return {course:'sia',lab:n<0?'ingresso':n>9?'conclusione':LABS[Math.floor(n/2)].id,screen:n,version:FORMAT,label:n<0?'Ingresso':n>9?'Conclusione':`${LABS[Math.floor(n/2)].label} · ${n%2+1}/2 · ${STAGES[n][0]}`};}
export function addNote(p,{role,kind,text}){text=String(text||'').trim().slice(0,2000);if(text.length<2)return null;const n={id:crypto.randomUUID(),projectId:p.id,...context(p),role:role==='docente'?'docente':'alunno',kind:['chiarezza','problema','idea','piaciuto'].includes(kind)?kind:'idea',text,createdAt:new Date().toISOString()};p.notes.push(n);return n;}
export function validProject(p){
 const ids=(v,a,exact=false)=>Array.isArray(v)&&new Set(v).size===v.length&&v.every(x=>a.some(y=>y.id===x))&&(!exact||v.length===a.length);
 const runs=(v,traced=false)=>Array.isArray(v)&&v.every(r=>r&&typeof r.signature==='string'&&(!traced||Array.isArray(r.trace)&&r.trace.every(t=>typeof t.label==='string'&&typeof t.text==='string')));
 return !!p&&p.format===FORMAT&&p.course==='sia'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(p.id)&&Number.isInteger(p.screen)&&p.screen>=-1&&p.screen<=10&&Number.isInteger(p.unlocked)&&p.unlocked>=0&&p.unlocked<=10&&Array.isArray(p.done)&&p.done.every(x=>Number.isInteger(x)&&x>=0&&x<10)&&Array.isArray(p.notes)&&p.notes.every(n=>n&&typeof n.text==='string')&&ids(p.interests,LABS)&&typeof p.title==='string'&&p.process&&ids(p.process.order,PROCESS,true)&&runs(p.process.runs,true)&&runs(p.process.handoffRuns)&&p.data&&ids(p.data.fields,FIELDS)&&[null,'Venerdì','Lunedì'].includes(p.data.missingDay)&&['Venerdì','Lunedì'].includes(p.data.filter)&&p.program&&ids(p.program.blocks,BLOCKS)&&runs(p.program.runs,true)&&['almeno','piu'].includes(p.program.condition)&&['conferma','attesa'].includes(p.program.yes)&&['conferma','attesa'].includes(p.program.no)&&p.ui&&ids(p.ui.order,PARTS,true)&&runs(p.ui.runs,true)&&typeof p.ui.title==='string'&&typeof p.ui.button==='string'&&['viola','verde','sole'].includes(p.ui.style)&&p.access&&runs(p.access.runs)&&ROLES.every(r=>typeof p.access.permissions?.[r.id]?.edit==='boolean'&&typeof p.access.permissions?.[r.id]?.view==='boolean');
}
